<x-layout>
<main class="ml-72 flex-1 mr-4 bg-[#161830] rounded-xl overflow-hidden">
            <div class="flex h-[calc(100vh-6rem)]">
                <!-- Chats List -->
                <div class="w-80 border-r border-gray-800">
                    <!-- Search Chats -->
                    <div class="p-4 border-b border-gray-800">
                        <div class="relative">
                            <input type="text" 
                                   placeholder="Search messages..." 
                                   class="w-full bg-[#0a0b1e] rounded-lg py-2 px-4 pl-10 focus:outline-none focus:ring-2 focus:ring-purple-500">
                            <i class="ri-search-line absolute left-3 top-2.5 text-gray-400"></i>
                        </div>
                    </div>

                    <!-- Chats -->
                    <div class="overflow-y-auto h-full pb-4" id="chatsList">
                        <!-- Active chat -->
                        <div class="p-4 bg-[#1c1f3a] cursor-pointer">
                            <div class="flex items-center gap-3">
                                <div class="relative">
                                    <div class="w-12 h-12 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 p-0.5">
                                        <div class="w-full h-full rounded-full bg-[#0a0b1e] p-0.5">
                                            <img src="akaza1.jpeg" alt="User" class="w-full h-full rounded-full object-cover">
                                        </div>
                                    </div>
                                    <div class="w-3 h-3 bg-green-500 rounded-full absolute bottom-0 right-0 border-2 border-[#1c1f3a]"></div>
                                </div>
                                <div class="flex-1">
                                    <div class="flex justify-between items-start">
                                        <h3 class="font-medium">Sarah Parker</h3>
                                        <span class="text-xs text-gray-400">2m</span>
                                    </div>
                                    <p class="text-sm text-gray-400 truncate">That's amazing! Can't wait to see...</p>
                                </div>
                            </div>
                        </div>

                        <!-- Other chats will be generated by JS -->
                    </div>
                </div>

                <!-- Chat Area -->
                <div class="flex-1 flex flex-col">
                    <!-- Chat Header -->
                    <div class="p-4 border-b border-gray-800 flex items-center justify-between">
                        <div class="flex items-center gap-3">
                            <div class="relative">
                                <div class="w-10 h-10 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 p-0.5">
                                    <div class="w-full h-full rounded-full bg-[#0a0b1e] p-0.5">
                                        <img src="akaza2.jpeg" alt="User" class="w-full h-full rounded-full object-cover">
                                    </div>
                                </div>
                                <div class="w-2.5 h-2.5 bg-green-500 rounded-full absolute bottom-0 right-0 border-2 border-[#161830]"></div>
                            </div>
                            <div>
                                <h3 class="font-medium">Sarah Parker</h3>
                                <p class="text-xs text-gray-400">Online</p>
                            </div>
                        </div>
                        <div class="flex items-center gap-4">
                            <button class="p-2 hover:bg-[#1c1f3a] rounded-lg transition-all">
                                <i class="ri-phone-line text-xl"></i>
                            </button>
                            <button class="p-2 hover:bg-[#1c1f3a] rounded-lg transition-all">
                                <i class="ri-vidicon-line text-xl"></i>
                            </button>
                            <button class="p-2 hover:bg-[#1c1f3a] rounded-lg transition-all">
                                <i class="ri-information-line text-xl"></i>
                            </button>
                        </div>
                    </div>

                    <!-- Messages Area -->
                    <div class="flex-1 overflow-y-auto p-4 space-y-4" id="messagesArea">
                        <!-- Messages will be generated by JS -->
                    </div>

                    <!-- Message Input -->
                    <div class="p-4 border-t border-gray-800">
                        <div class="flex items-center gap-4">
                            <button class="p-2 hover:bg-[#1c1f3a] rounded-lg transition-all">
                                <i class="ri-image-line text-xl"></i>
                            </button>
                            <button class="p-2 hover:bg-[#1c1f3a] rounded-lg transition-all">
                                <i class="ri-emotion-happy-line text-xl"></i>
                            </button>
                            <div class="flex-1 relative">
                                <input type="text" 
                                       placeholder="Type a message..." 
                                       class="w-full bg-[#0a0b1e] rounded-lg py-2 px-4 pr-10 focus:outline-none focus:ring-2 focus:ring-purple-500">
                                <button class="absolute right-2 top-2 p-1 hover:bg-[#1c1f3a] rounded-lg transition-all">
                                    <i class="ri-send-plane-fill text-xl text-blue-500"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    @push('scripts')
    @vite('resources/js/index.js')
    @vite('resources/js/messages.js')
    @endpush
</x-layout>